name: 'LinkCanary'
description: 'Crawl sitemap and fail builds on broken links'
author: 'LinkCanary'

branding:
  icon: 'link'
  color: 'yellow'

inputs:
  sitemap-url:
    description: 'URL to the sitemap.xml file'
    required: true
  fail-on-priority:
    description: 'Exit 1 if issues at or above this priority level (critical/high/medium/low/none)'
    required: false
    default: 'high'
  max-pages:
    description: 'Limit pages to crawl (0 = no limit)'
    required: false
    default: '0'
  skip-ok:
    description: 'Exclude 200 OK links from report'
    required: false
    default: 'true'
  delay:
    description: 'Seconds between requests'
    required: false
    default: '0.5'
  timeout:
    description: 'Request timeout in seconds'
    required: false
    default: '10'
  webhook-url:
    description: 'Optional webhook URL for notifications (Slack/Discord/Generic)'
    required: false
    default: ''

outputs:
  total-issues:
    description: 'Count of issues found'
  critical-count:
    description: 'Critical issues count'
  high-count:
    description: 'High priority count'
  medium-count:
    description: 'Medium priority count'
  low-count:
    description: 'Low priority count'
  report-path:
    description: 'Path to CSV report'

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.sitemap-url }}
