name: 'LinkCanary'
description: 'Crawl sitemap and fail builds on broken links'
author: 'LinkCanary'

branding:
  icon: 'link'
  color: 'yellow'

inputs:
  sitemap-url:
    description: 'URL to the sitemap.xml file (required unless using --url or --urls-file)'
    required: false
    default: ''
  url:
    description: 'Check a single URL instead of sitemap (for quick CI checks)'
    required: false
    default: ''
  urls-file:
    description: 'Path to file with URLs to check (one per line). Useful for checking changed pages in PRs.'
    required: false
    default: ''
  fail-on-priority:
    description: 'Exit 1 if issues at or above this priority level (critical/high/medium/low/none)'
    required: false
    default: 'high'
  max-pages:
    description: 'Limit pages to crawl (0 = no limit)'
    required: false
    default: '0'
  skip-ok:
    description: 'Exclude 200 OK links from report'
    required: false
    default: 'true'
  delay:
    description: 'Seconds between requests'
    required: false
    default: '0.5'
  timeout:
    description: 'Request timeout in seconds'
    required: false
    default: '10'
  max-retries:
    description: 'Max retries for transient errors (502/503/504). Set to 0 to disable.'
    required: false
    default: '3'
  retry-delay:
    description: 'Initial delay between retries in seconds'
    required: false
    default: '1.0'
  retry-backoff:
    description: 'Multiplier for exponential backoff'
    required: false
    default: '2.0'
  format:
    description: 'Export format (csv/json/mdx/xlsx/pdf)'
    required: false
    default: 'csv'
  exclude-pattern:
    description: 'Exclude URLs matching pattern (newline-separated). E.g., *linkedin.com*, *.pdf'
    required: false
    default: ''
  include-pattern:
    description: 'Only check URLs matching pattern (newline-separated). E.g., /blog/*, /docs/*'
    required: false
    default: ''
  pattern-type:
    description: 'Pattern matching type (glob or regex)'
    required: false
    default: 'glob'
  # Authentication for protected sites
  auth-user:
    description: 'Username for HTTP Basic Authentication (for staging sites)'
    required: false
    default: ''
  auth-pass:
    description: 'Password for HTTP Basic Authentication (use secrets!)'
    required: false
    default: ''
  auth-header:
    description: 'Custom Authorization header (e.g., "Bearer ${{ secrets.API_TOKEN }}")'
    required: false
    default: ''
  cookie:
    description: 'Cookie string for authenticated sessions (e.g., "session=abc123")'
    required: false
    default: ''
  webhook-url:
    description: 'Optional webhook URL for notifications (Slack/Discord/Generic)'
    required: false
    default: ''

outputs:
  total-issues:
    description: 'Count of issues found'
  critical-count:
    description: 'Critical issues count'
  high-count:
    description: 'High priority count'
  medium-count:
    description: 'Medium priority count'
  low-count:
    description: 'Low priority count'
  report-path:
    description: 'Path to report file'

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.sitemap-url }}
