"""CLI for generating HTML reports from CSV files."""

import argparse
import os
import sys

from . import __version__
from .html_reporter import HTMLReportGenerator


def create_parser() -> argparse.ArgumentParser:
    """Create the argument parser."""
    parser = argparse.ArgumentParser(
        prog='linkcheck-report',
        description='Generate an interactive HTML report from a LinkCanary CSV file.',
        epilog='Example: linkcheck-report link_report.csv --output report.html --open',
    )
    
    parser.add_argument(
        'csv_file',
        help='Path to the CSV file generated by linkcheck',
    )
    
    parser.add_argument(
        '-o', '--output',
        default=None,
        help='Output HTML file path (default: <csv_file>.html)',
    )
    
    parser.add_argument(
        '--open',
        action='store_true',
        help='Open report in browser after generation',
    )
    
    parser.add_argument(
        '--version',
        action='version',
        version=f'%(prog)s {__version__}',
    )
    
    return parser


def main(args=None):
    """Main entry point."""
    parser = create_parser()
    parsed_args = parser.parse_args(args)
    
    if not os.path.exists(parsed_args.csv_file):
        print(f"Error: File not found: {parsed_args.csv_file}")
        return 1
    
    output_path = parsed_args.output
    if output_path is None:
        base = os.path.splitext(parsed_args.csv_file)[0]
        output_path = f"{base}.html"
    
    print(f"Loading CSV: {parsed_args.csv_file}")
    
    try:
        reporter = HTMLReportGenerator()
        reporter.load_csv(parsed_args.csv_file)
        reporter.generate_html(output_path, open_browser=parsed_args.open)
        print(f"HTML report saved to: {output_path}")
        
        if reporter.summary:
            total = reporter.summary.get('total', 0)
            critical = reporter.summary['by_priority'].get('critical', 0)
            high = reporter.summary['by_priority'].get('high', 0)
            print(f"Total issues: {total} (Critical: {critical}, High: {high})")
        
        return 0
    except Exception as e:
        print(f"Error: {e}")
        return 1


if __name__ == '__main__':
    sys.exit(main())
