"""Initial baseline schema (crawls, webhooks).

Creates the current model tables from SQLAlchemy metadata so Alembic owns the
schema going forward. Subsequent migrations should be autogenerated against a
live database (``alembic revision --autogenerate``).

Revision ID: 0001_initial
Revises:
Create Date: 2026-06-01
"""
from typing import Sequence, Union

from alembic import op

from linkcanary_ui.models import Base
import linkcanary_ui.models.crawl  # noqa: F401
import linkcanary_ui.models.webhook  # noqa: F401

revision: str = "0001_initial"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    Base.metadata.create_all(bind=op.get_bind())


def downgrade() -> None:
    Base.metadata.drop_all(bind=op.get_bind())
